# Author:  DINDIN Meryll
# Date:    09 July 2019
# Project: AsTeR

users:
- username: 'admin'
  password: 'admin'
  firstname: 'admin'
  lastname: 'admin'
  email: 'admin@berkeley.edu'
- username: 'guest'
  password: 'guest'
  firstname: 'guest'
  lastname: 'guest'
  email: 'guest@berkeley.edu'

units:
- unit_id: '310bee28ecb9459e9184ed226d729d1f'
  unit_type: 'police'
  unit_name: 'Police Patrol | Unit 3'
  longitude: -122.42036500000002
  latitude: 37.729621
  status: 'active'
  target: '-122.4284612378737:37.75182473669415'
  path: 'none'
- unit_id: '340bb30f0d8d49169c5218c6a3f4ca2c'
  unit_type: 'ambulance'
  unit_name: 'Ambulance | Unit 7'
  longitude: -122.38736800000001
  latitude: 37.725353999999996
  status: 'active'
  target: 'none'
  path: 'none'
- unit_id: '5d87b0f6ae464929adb491099fdf4d33'
  unit_type: 'firefighter'
  unit_name: 'Firefighters | Unit 5'
  longitude: -122.414635
  latitude: 37.794046
  status: 'active'
  target: 'none'
  path: 'none'
